version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./chroma_db:/app/chroma_db
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json:ro
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=52428800
      - CHROMA_PERSIST_DIR=./chroma_db
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    depends_on:
      - redis
    networks:
      - skillsheet-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skillsheet-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - app
    networks:
      - skillsheet-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  skillsheet-network:
    driver: bridge
